pxblog-master/web/router.ex
defmodule Pxblog.Router do
  use Pxblog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Pxblog.CurrentUserPlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Pxblog do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/posts", PostController, only: [:index]

    resources "/posts", PostController, only: [] do
      resources "/comments", CommentController, only: [:create, :delete, :update]
    end

    resources "/users", UserController do
      resources "/posts", PostController
    end
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Pxblog do
  #   pipe_through :api
  # end
end

pxblog-master/web/views/layout_view.ex
defmodule Pxblog.LayoutView do
  use Pxblog.Web, :view

  def current_user(conn) do
    Plug.Conn.get_session(conn, :current_user)
  end
end

pxblog-master/web/templates/layout/alerts.html.eex
<div class="row alerts">
  <%= if flash = get_flash(@conn, :info) do %>
    <div class="success callout alert-info" role="alert">
      <%= flash %>
    </div>
  <% end %>

  <%= if flash = get_flash(@conn, :error) do %>
    <div class="alert callout alert-error" role="alert">
      <%= flash %>
    </div>
  <% end %>
</div>

pxblog-master/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <%= render "head.html", conn: @conn %>

  <body>
    <%= render "navigation.html", conn: @conn %>

    <section class="main-content row expanded">
      <%= render "alerts.html", conn: @conn %>

      <div class="row content">
        <%= render @view_module, @view_template, assigns %>
      </div>
    </section>

    <%= render "script.html", conn: @conn %>
  </body>
</html>

pxblog-master/web/templates/layout/head.html.eex
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="A Tech Blog Written in Elixir and Phoenix">
  <meta name="author" content="Brandon Richey">
  <%= if current_user = @conn.assigns[:current_user] do %>
    <%= tag :meta, name: "channel_token", content: Phoenix.Token.sign(@conn, "user", current_user.id) %>
  <% end %>

  <title>Phoenix Tech Blog</title>
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
</head>

pxblog-master/web/templates/layout/navigation.html.eex
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="menu">
      <li class="logo">
        Phoenix Tech Blog
      </li>
      <li>
        <%= link "Home", to: page_path(@conn, :index) %>
      </li>
      <li>
        <%= link "Posts", to: post_path(@conn, :index) %>
      </li>
      <%= if current_user = @conn.assigns[:current_user] do %>
        <li>
          <%= link "My Posts", to: user_post_path(@conn, :index, current_user.id) %>
        </li>
        <li>
          <%= link "New Post", to: user_post_path(@conn, :new, current_user.id) %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
        <%= if current_user = @conn.assigns[:current_user] do %>
          <li>
            <%= link current_user.username, to: user_path(@conn, :edit, current_user.id) %>
          </li>
          <li>
            <%= link "Logout", to: session_path(@conn, :delete, current_user.id), method: :delete, class: "button alert" %>
          </li>
        <% else %>
          <li>
            <%= link "Login", to: session_path(@conn, :new), class: "button" %>
          </li>
        <% end %>
      </li>
    </ul>
  </div>
</div>

pxblog-master/web/templates/layout/script.html.eex
<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
<script type="text/javascript">
  $(function() {
    $(document).foundation();
  });
</script>

pxblog-master/web/templates/layout/splash.html.eex
<!DOCTYPE html>
<html lang="en">
  <%= render "head.html", conn: @conn %>

  <body>
    <%= render "navigation.html", conn: @conn %>

    <section class="main-content row expanded">
      <%= render "alerts.html", conn: @conn %>

      <section class="text-center image-overlay row content">
        <%= render @view_module, @view_template, assigns %>
      </section>

      <section class="about expanded row">
        <div class="columns medium-12 large-4">
          <div class="icon">
            <i class="fi-like"></i>
          </div>
          <h2>What Powers This Blog</h2>
          <p>
            This blog is powered by <a href="http://elixir-lang.org">Elixir</a> and <a href="http://phoenixframework.org">Phoenix Framework</a> to
            give us a super fast, super clean, and super fun to modify blog engine!
          </p>
        </div>
        <div class="columns medium-12 large-4">
          <div class="icon">
            <i class="fi-comments"></i>
          </div>
          <h2>We Support Live Comments</h2>
          <p>
            By using the latest and greatest in client and server technology, we're able to offer a live, realtime commenting system with nearly no impact
            to performance!
          </p>
        </div>
        <div class="columns medium-12 large-4">
          <div class="icon">
            <i class="fi-pencil"></i>
          </div>
          <h2>We Support Markdown</h2>
          <p>
            We allow you to use <a href="https://daringfireball.net/projects/markdown/">Markdown</a> in all of your posts, which will make it simple to write
            up each post in the program of your choice and import it into this blog!
          </p>
        </div>
      </section>

      <section class="more-info expanded row">
        This is an example design for the Phoenix Blog Engine project detailed in my series of
        <a href="https://medium.com/@diamondgfx/introduction-fe138ac6079d">Medium</a> posts.
        This design is merely a starting template; you may want to go out and find your own
        as well to make it look truly original! You're welcome to use the source code for this
        project as well as the design as you wish! If you're interested in more, please find me
        on the internet via:
        <br />
        <div class="social-media text-center">
          <a href="http://twitter.com/diamondgfx"><i class="fi-social-twitter"></i></a>
          <a href="https://medium.com/@diamondgfx/"><i class="fi-social-medium"></i></a>
        </div>
      </section>

      <footer class="expanded row">
        I'm a standard footer for your site! Maybe you can throw a copyright &copy; down here or something like that, or licensing! You know, whatever!
      </footer>
    </section>

    <%= render "script.html", conn: @conn %>
  </body>
</html>